[holbuild]
schema = 2
minimum_version = "0.8.1"

[project]
name = "verifereum"
version = "1.0.0"

[build]
roots = ["verifereumScript.sml"]
exclude = ["tests/defs/*", "tests/results/*"]
tactic_timeout = 30

[dependencies.hol]
git = "https://github.com/HOL-Theorem-Prover/HOL.git"
rev = "1d9f33ad168d3823cc070223d83ea660d86dcb58"

[dependencies.holexamples]
from = "hol"
path = "."
manifest = "holexamples.manifest.toml"
