[holbuild]
minimum_version = "0.10.2"

[project]
name = "verifereum"
version = "1.0.3"

[build]
roots = ["verifereumScript.sml"]
exclude = ["tests/defs", "tests/results"]
tactic_timeout = 30

[dependencies.hol]
git = "https://github.com/HOL-Theorem-Prover/HOL.git"
rev = "f18e6e7277c2648d40c2491d87f09083c909e6e9"

[dependencies.holexamples]
from = "hol"
path = "."
manifest = "holexamples.manifest.toml"
