[holbuild]
minimum_version = "0.11.2"

[project]
name = "verifereum"
version = "1.0.3"

[build]
roots = ["verifereumScript.sml"]
tactic_timeout = 30

[build.groups.tests]
include = ["tests/defs", "tests/results"]

[[executable]]
name = "runtests"
output = "tests/runtests.exe"
objects = ["runtests"]

[dependencies.hol]
git = "https://github.com/HOL-Theorem-Prover/HOL.git"
rev = "0164336eedbe0be7b33e333e854454f469ede4b2"

[dependencies.holexamples]
from = "hol"
path = "."
manifest = "holexamples.manifest.toml"
