Theory vfmTestDefs0796[no_sig_docs]
Libs vfmTestAuxLib vfmTestDefLib
val () = holbuild_extra_deps ["../fixtures/blockchain_tests/for_osaka/ported_static/stInitCodeTest/call_contract_to_create_contract_which_would_create_contract_in_init_code/call_contract_to_create_contract_which_would_create_contract_in_init_code.json"];
val tests = json_path_to_tests (vfmTestAuxLib.fixtures_path "blockchain_tests/for_osaka/ported_static/stInitCodeTest/call_contract_to_create_contract_which_would_create_contract_in_init_code/call_contract_to_create_contract_which_would_create_contract_in_init_code.json");
val defs = mapi (define_test "0796") tests;
