Theory vfmTestDefs1989[no_sig_docs]
Libs vfmTestAuxLib vfmTestDefLib
val () = holbuild_extra_deps ["../fixtures/blockchain_tests/for_osaka/ported_static/stStaticCall/static_contract_creation_oo_gdont_leave_empty_contract_via_transaction/static_contract_creation_oo_gdont_leave_empty_contract_via_transaction.json"];
val tests = json_path_to_tests (vfmTestAuxLib.fixtures_path "blockchain_tests/for_osaka/ported_static/stStaticCall/static_contract_creation_oo_gdont_leave_empty_contract_via_transaction/static_contract_creation_oo_gdont_leave_empty_contract_via_transaction.json");
val defs = mapi (define_test "1989") tests;
