Theory vfmTestDefs1988[no_sig_docs]
Libs vfmTestAuxLib vfmTestDefLib
val () = holbuild_extra_deps ["../fixtures/blockchain_tests/for_osaka/ported_static/stStaticCall/static_contract_creation_make_call_that_ask_more_gas_then_transaction_provided/static_contract_creation_make_call_that_ask_more_gas_then_transaction_provided.json"];
val tests = json_path_to_tests (vfmTestAuxLib.fixtures_path "blockchain_tests/for_osaka/ported_static/stStaticCall/static_contract_creation_make_call_that_ask_more_gas_then_transaction_provided/static_contract_creation_make_call_that_ask_more_gas_then_transaction_provided.json");
val defs = mapi (define_test "1988") tests;
