Theory vfmTestDefs1787[no_sig_docs]
Libs vfmTestAuxLib vfmTestDefLib
val () = holbuild_extra_deps ["../fixtures/blockchain_tests/for_osaka/ported_static/stStaticCall/static_call_contract_to_create_contract_which_would_create_contract_if_called/static_call_contract_to_create_contract_which_would_create_contract_if_called.json"];
val tests = json_path_to_tests (vfmTestAuxLib.fixtures_path "blockchain_tests/for_osaka/ported_static/stStaticCall/static_call_contract_to_create_contract_which_would_create_contract_if_called/static_call_contract_to_create_contract_which_would_create_contract_if_called.json");
val defs = mapi (define_test "1787") tests;
